# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc9f01a3f86fce6ec1480dfde42ecf52c89b4f44136f3a371bdbe2c83ecb527d4ac9c07e5a6258a882f67e7bba0560abed8084a569e922a24a54f8c49afc2469

test:
  secret_key_base: db72d7d1bc60b824afb338c8ede8087727507b3723ba66c54cea759f61f835bd09a08326433d594c41a884bc90b65ac2a83244e5ad47eff8d8a9511ec3bd8bfb

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

