export default {
  ENTITY_ACCESS: 'ENTITY_ACCESS',
  ENTITY_READ: 'ENTITY_READ',
  ADD_STATEMENT_NEXT_STEP: 'ADD_STATEMENT_NEXT_STEP',
  ADD_STATEMENT_PUBLIC_FIGURE_SELECTION: 'ADD_STATEMENT_PUBLIC_FIGURE_SELECTION',
  ADD_STATEMENT_SUBJECT_SELECTION: 'ADD_STATEMENT_SUBJECT_SELECTION',
  ADD_STATEMENT_POSITION_SELECTION: 'ADD_STATEMENT_POSITION_SELECTION',
  ADD_STATEMENT_UPDATE_EVIDENCE_URL: 'ADD_STATEMENT_UPDATE_EVIDENCE_URL',
  ADD_STATEMENT_UPDATE_EVIDENCE_FILE: 'ADD_STATEMENT_UPDATE_EVIDENCE_FILE',
  ADD_STATEMENT_VALIDATE: 'ADD_STATEMENT_VALIDATE',
};
