defaults: &defaults

  ranks:
    new_user:                  0     # ==> Can add statement, evidence
    participate_in_beta:    1000     # ==> Can declare bugs, give feedback, ...
    confirmed_user:         1000     # ==> Can add subjects, position
    moderator:             10000     # ==> Can delete major subjects, major public figures, positions, statements, ...
    founder:             1000000
    dummies:                -400     # ==> Miséricorde 
    spammers:               -500

  can:
    ## New users (0)
    add_statement: new_user
    add_evidence: new_user
    add_position: new_user
    
    ## dummies (-400)
    add_statement: dummies
    add_evidence: dummies
    add_position: dummies
    
    ## Confirmed users (1000)
    add_subject: confirmed_user
    add_personality: confirmed_user
    approve_subject: confirmed_user 
    approve_personality: confirmed_user
    approve_evidentce: confirmed_user
    approve_argument: confirmed_user
    approve_position: confirmed_user
    reject_subject: confirmed_user # ==> Rejecting is the equivalent to signaling the fallacy in the element, but only Moderators will actually be able to delete it
    reject_personality: confirmed_user
    reject_evidentce: confirmed_user
    reject_argument: confirmed_user
    reject_position: confirmed_user

    ## Moderators (10000)
    delete_minor_subject: moderator # ==> Minor subject: less than 1 week old, or less than 5 arguments
    delete_minor_personality: moderator # ==> Minor personality: less than 1 week old, or less than 2 arguments
    delete_evidentce: moderator
    delete_argument: moderator
    delete_position: moderator
    edit_argument: moderator # ==> Includes description 
    edit_subject: moderator # ==> Includes description 
    edit_personality: moderator # ==> Includes description 

    ## Founder
    delete_major_subject: founder 
    delete_major_personality: founder
    
    
## INSPIRATION : https://stackoverflow.com/help/privileges?tab=all

  actions_to_reputation:
    signed_up:            5
    founder:        1000000
    early_bird:       10000
    blogged_about:     1000

    added_subject:          50
    added_subject_valided: 200   # to the poster of subject
    added_personality_valided: 50 
    validated_subject:       50   # to the validator
    validated_personality:   50   # to the validator
    validated_statement:     50   # to the validator
    validated_argument:      50   # to the validator
    validated_position:      50   # to the validator

    edited_subject:          5
    added_statement_valided:         50
    added_evidence_valided:          50
    added_argument_valided:          50
    added_position_valided:          50

    linked_argument_to_statement: 1

    subject_is_rejected_spam: -1000
    subject_is_rejected_duplicate: -100
    subject_is_rejected_off_topic: -100
    personality_is_rejected_spam: -1000
    personality_is_rejected_duplicate: -100
    personality_is_rejected_off_topic: -100
    statement_is_rejected: -100
    evidence_is_rejected: -100
    argument_is_rejected: -100
    position_is_rejected: -100
    argument_to_statement_link_is_rejected: -100

## INSPIRATION : https://stackoverflow.com/help/whats-reputation


development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults