-- No-op : la migration 20260321120000 a été corrigée avant déploiement pour
-- utiliser stated_at et renommer les contraintes FK directement.
-- Cette migration n'était nécessaire que pour les bases locales qui avaient
-- la version originale (avec la colonne "date"). Elle est conservée comme
-- migration vide pour ne pas casser l'historique local.
